### ISSUE TITLE
Healenium without docker for Selenium in .NET

### ISSUE THREAD

**Issue by hemanth-tr** [healenium/healenium-example-dotnet#3]
Hi,

As mentioned in Healenium.io site, I followed the following steps to install the necessary services in the windows server. After this, what would be the proxy or nodeUrl to run the tests using C# .NET?

![image](https://user-images.githubusercontent.com/24373661/172723157-b680301f-12e5-48e9-ba0d-f057c7438fad.png)

**Comment by ElenaStepuro** [comment]
Hello @hemanth-tr This instruction is for java. For C# you can find tutorial here: https://healenium.io/docs#rec427873399
