### ISSUE TITLE
Mis typo in the solution/project file name 

### ISSUE THREAD

**Issue by nvborisenko** [healenium/healenium-example-dotnet#4]
### Describe the bug

[Healenuim.NET.csproj](https://github.com/healenium/healenium-example-dotnet/blob/master/Healenuim.NET.csproj)

Should be : Healenium

### How to reproduce the issue

```shell
-
```

### Logs appeared during using Healenium

```shell
-
```

### Expected behavior

-

### Healenium Proxy version

-

### Healenium Backend version

-

**Comment by ElenaStepuro** [comment]
Hello @nvborisenko Could be describe the bug?

**Comment by nvborisenko** [comment]
![image](https://user-images.githubusercontent.com/22616990/179716003-02994444-1cef-4d6a-a9aa-d9ef8ef85f86.png)

**Comment by ElenaStepuro** [comment]
Resolved
